#: kivy 1.8.0
#: import Window kivy.core.window.Window

<SnakePart>:
    canvas:
        Color:
            rgb: self.color if self.color != [] else (1, 1, 1)
        Ellipse:
            pos: self.pos
            size: self.size
        Ellipse:
            pos: self.pos[0] % Window.width, self.pos[1] % Window.height
            size: self.size

<SnakeFoo>:
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size